# Generated by Django 2.1.5 on 2019-02-11 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
