# Generated by Django 2.1.5 on 2019-02-11 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_challenge', models.TextField(max_length=100)),
                ('banyak_soal', models.CharField(max_length=100)),
                ('bobot_nilai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Direksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.TextField(max_length=50)),
                ('no_telepon', models.IntegerField()),
                ('jabatan', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Live_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_live_code', models.TextField(max_length=50)),
                ('banyak_soal', models.CharField(max_length=50)),
                ('bobot_nilai', models.CharField(max_length=50)),
                ('tanggal_pelaksanaan', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.TextField(max_length=100)),
                ('jadwal_dimulai', models.CharField(max_length=100)),
                ('jadwal_berakhir', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.TextField(max_length=50)),
                ('no_telepon', models.IntegerField()),
                ('no_absen', models.IntegerField()),
                ('nilai_rata_rata', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.TextField(max_length=50)),
                ('no_telepon', models.IntegerField()),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.MataPelajaran')),
            ],
        ),
        migrations.AddField(
            model_name='live_code',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.MataPelajaran'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.MataPelajaran'),
        ),
    ]
